CREATE TYPE public.post_status AS ENUM ('draft', 'published', 'archived');
CREATE TYPE public.post_visibility AS ENUM ('public', 'private', 'unlisted');
CREATE TRIGGER update_posts_updated_at BEFORE UPDATE ON public.partners FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TABLE public.post_categories (id uuid DEFAULT gen_random_uuid() NOT NULL, name text NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone, slug text NOT NULL);
ALTER TABLE public.post_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.post_categories ADD CONSTRAINT post_categories_name_key UNIQUE (name);
ALTER TABLE public.post_categories ADD CONSTRAINT post_categories_pkey PRIMARY KEY (id);
ALTER TABLE public.post_categories ADD CONSTRAINT post_categories_slug_key UNIQUE (slug);
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.post_categories TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.post_categories TO authenticated;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.post_categories TO service_role;
CREATE TABLE public.post_tags (post_id uuid NOT NULL, tag_id uuid NOT NULL);
ALTER TABLE public.post_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.post_tags ADD CONSTRAINT post_tags_pkey PRIMARY KEY (post_id, tag_id);
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.post_tags TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.post_tags TO authenticated;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.post_tags TO service_role;
CREATE TABLE public.posts (id uuid DEFAULT gen_random_uuid() NOT NULL, title text NOT NULL, slug text NOT NULL, excerpt text, content jsonb, content_html text, cover_image_url text, published_at timestamp with time zone, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone DEFAULT now(), user_id uuid NOT NULL, status public.post_status DEFAULT 'draft'::public.post_status NOT NULL, visibility public.post_visibility DEFAULT 'public'::public.post_visibility NOT NULL);
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posts ADD CONSTRAINT posts_pkey PRIMARY KEY (id);
ALTER TABLE public.post_tags ADD CONSTRAINT post_tags_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.posts(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public.posts ADD CONSTRAINT posts_slug_key UNIQUE (slug);
ALTER TABLE public.posts ADD CONSTRAINT posts_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE RESTRICT;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.posts TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.posts TO authenticated;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.posts TO service_role;
CREATE POLICY "Enable read access for all users" ON public.posts FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Enable read access for users based on user_id" ON public.posts FOR SELECT TO authenticated USING (true);
CREATE TABLE public.tags (id uuid DEFAULT gen_random_uuid() NOT NULL, name text NOT NULL, slug text NOT NULL, created_at timestamp with time zone DEFAULT now() NOT NULL, updated_at timestamp with time zone);
ALTER TABLE public.tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tags ADD CONSTRAINT tags_name_key UNIQUE (name);
ALTER TABLE public.tags ADD CONSTRAINT tags_pkey PRIMARY KEY (id);
ALTER TABLE public.post_tags ADD CONSTRAINT post_tags_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.tags(id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE public.tags ADD CONSTRAINT tags_slug_key UNIQUE (slug);
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.tags TO anon;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.tags TO authenticated;
GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.tags TO service_role;
